// Confluence Documentation URLs
const businessGlossaryUrl = `https://carecom.atlassian.net/wiki/spaces/DATA/pages/1460914799/Business+Glossary`
const lingoUrl = `https://carecom.atlassian.net/wiki/spaces/czen/pages/6390022556/Lingo`
const providerTermsUrl = `https://carecom.atlassian.net/wiki/spaces/PS/pages/4811730401/Glossary+of+Provider+Terms`
// Other URLs
const kindsOfUrlsUrl = `https://carecom.atlassian.net/wiki/spaces/PROD/pages/4604264991/Kinds+of+URLs`
const productManagementUrl = `https://wiki.infra.carezen.net/display/PdM/Product+Management+Center+of+Excellence`
const careSmartsUrl = `https://www.care.com/q/`
const careMatchAndCareRankUrl = `https://carecom.atlassian.net/wiki/spaces/PROD/pages/4611410330/Care+Match+and+Care+Rank`
const careCoreUrl = `http://care.com/c/`
const teenProviderGuidelinesUrl = `https://carecom.atlassian.net/wiki/spaces/PdM/pages/4912691619/Teen+Provider+Guidelines`
const payToUnlockUrl = `https://carecom.atlassian.net/wiki/spaces/PS/pages/4811729004/Pay+to+Unlock`
const tinderUrl = `https://carecom.atlassian.net/wiki/spaces/PS/pages/4811729006/Tinder`


// TODO - handle duplicate keys, i.e., 'CBUC' => child and consumer...
const terms = {
  // Generic and Carecore
  'AB Tasty': { content: businessGlossaryUrl, description: `3rd party multi-variate testing tool` },
  'Activate': { content: businessGlossaryUrl, description: `Consulting agency that did market research for the company in 2019` },
  'Active Premium': { content: businessGlossaryUrl, description: `A premium can downgrade, but an active premium is currently not downgraded.` },
  'Adaptive': { content: businessGlossaryUrl, description: `Financial software from 8 years ago, ~2012` },
  'AG': { content: businessGlossaryUrl, description: `Attorney General, some state AGs have mandated certain Care.com disclosures` },
  'Al Fresco': { content: businessGlossaryUrl, description: `Internal CMS & community platform` },
  'Amplitude': { content: businessGlossaryUrl, description: `Annual operating plan, e.g. the budget` },
  'AOP': { content: businessGlossaryUrl, description: `Annual operating plan, e.g. the budget` },
  'ARPU': { content: businessGlossaryUrl, description: `Avg Revenue per User` },
  'Background Check': { content: businessGlossaryUrl, description: `A series of checks we run on (mainly) providers encompassing criminal history checks, sex offender registry checks, motor vehicle record checks. A BGC is requested -> Approved -> Executed -> Billed.` },
  'Backup Care': { content: businessGlossaryUrl, description: `Aka BUC and CBUC, service that Care@Work provides` },
  'Basic Check': { content: businessGlossaryUrl, description: `aka “Under the Hood Check” - a shorter, database background check that is run on Premium Seekers` },
  'BP CVR': { content: businessGlossaryUrl, description: `Basic to Premium CVR` },
  'B2P': { content: businessGlossaryUrl, description: `Basic to Premium` },
  'Bravo': { content: businessGlossaryUrl, description: `New, modular technical platform on which new Care.com is being built as of 2020` },
  'Bright Horizons': { content: businessGlossaryUrl, description: `Bright Care@Work competitor in backup childcare space; runs childcare centers` },
  'BUC': { content: businessGlossaryUrl, description: `Back-up care, aka CBUC` },
  'CBUC': { content: businessGlossaryUrl, description: `Child Back-up Care, Care@Work service shut down in Mar 2020?` },
  'Care Hub': { content: businessGlossaryUrl, description: `aka Family Care Hub` },
  'CareCheck': { content: businessGlossaryUrl, description: `A form of background check and name of initiative to have background checks on all active providers on Care.com` },
  'C@W': { content: businessGlossaryUrl, description: `aka Care@Work, B2B` },
  'Care@Work': { content: businessGlossaryUrl, description: `B2B` },
  'Caregiver': { content: businessGlossaryUrl, description: `Aka “provider” or person who is seeking employment on Care.com` },
  'CC': { content: businessGlossaryUrl, description: `Child Care` },
  'CPB': { content: businessGlossaryUrl, description: `Cost per basic member acquisition` },
  'CPU': { content: businessGlossaryUrl, description: `Cost per visit acquisition` },
  'CRM': { content: businessGlossaryUrl, description: `Customer Relationship Mgmt team, responsible for emails` },
  'CSR': { content: businessGlossaryUrl, description: `Internal tool for Member Care to process requests, jobs and issues.` },
  'CVR': { content: businessGlossaryUrl, description: `Conversion Rate` },
  'E-bureau check': { content: businessGlossaryUrl, description: `E-bureau Vendor who does lighter-weight background checks` },
  'Enrollment': { content: businessGlossaryUrl, description: `Initial member onboarding flow for creating an account` },
  'FCC': { content: businessGlossaryUrl, description: `Family Child Care - childcare businesses usually located at people's personal homes` },
  'Family Care Hub': { content: businessGlossaryUrl, description: `Family Care C@W, Senior Care product that lets families share documents, coordinate care for a family member` },
  'Figma': { content: businessGlossaryUrl, description: `3rd party design tool for collaboration` },
  'Figure8': { content: businessGlossaryUrl, description: `Transportation start-up acquired by Care, shut down in Aug 2019` },
  'Galore': { content: businessGlossaryUrl, description: `Kid after-school activities, camp directory company acquired by Care.com` },
  'Hanover': { content: businessGlossaryUrl, description: `3rd party user research firm` },
  'Hawk Partners': { content: businessGlossaryUrl, description: `3rd party user research firm` },
  'HK': { content: businessGlossaryUrl, description: `Housekeeping` },
  'Home Page': { content: businessGlossaryUrl, description: `Member Home Page (logged in) and Visitor Home Page (not logged in)` },
  'HomePay': { content: businessGlossaryUrl, description: `Payroll service company acquired by Care.com` },
  'Instantbook': { content: businessGlossaryUrl, description: `See Request to Book` },
  'Invision': { content: businessGlossaryUrl, description: `3rd party design tool` },
  'Iterable': { content: businessGlossaryUrl, description: `ESP, email service provider` },
  'Kochava': { content: businessGlossaryUrl, description: `Mobile app analytics tool` },
  'LOPT': { content: businessGlossaryUrl, description: `Length of paid time` },
  'Marketplace': { content: businessGlossaryUrl, description: `Business that enables businesses to search and recruit for providers and market to seekers. Daycares and Senior Care Agencies are the biggest example of these. These include SMB (Small Business) and National Account (contracts with larger daycare brands like LCG - Learning Care Group)` },
  'Match': { content: businessGlossaryUrl, description: `UX of matching seekers and providers` },
  'Matching': { content: businessGlossaryUrl, description: `UX of matching seekers and providers` },
  'Member': { content: businessGlossaryUrl, description: `Care.com user` },
  'Member Care': { content: businessGlossaryUrl, description: `Customer service team` },
  'Member Home Page': { content: businessGlossaryUrl, description: `Logged in user home page` },
  'MHP': { content: businessGlossaryUrl, description: `Member Home Page` },
  'Miro': { content: businessGlossaryUrl, description: `3rd party whiteboarding tool` },
  'Mitek': { content: businessGlossaryUrl, description: `3rd party ID verification vendor` },
  'Monetate': { content: businessGlossaryUrl, description: `Multi-variate testing tool, also used by CRM team for posting of on-site banners` },
  'MSI': { content: businessGlossaryUrl, description: `internal database` },
  'MVC': { content: businessGlossaryUrl, description: `Motor Vehicle Check` },
  'NDWA': { content: businessGlossaryUrl, description: `National Domestic Workers Alliance` },
  'NPS': { content: businessGlossaryUrl, description: `Net Promoter Score` },
  'NSOPW': { content: businessGlossaryUrl, description: `National Sex Offender Public Website` },
  'OKR': { content: businessGlossaryUrl, description: `Objectives & Key Results` },
  'OOH': { content: businessGlossaryUrl, description: `Out of home` },
  'PAJ': { content: businessGlossaryUrl, description: `Post a job` },
  'Parents in a pinch': { content: businessGlossaryUrl, description: `Boston nanny agency acquired by Care to meet enterprise SLAs. Often Called PIAP` },
  'PIAP': { content: businessGlossaryUrl, description: `Abbreviation for Parents in a pinch` },
  'PC': { content: businessGlossaryUrl, description: `Pet Care` },
  'PFI': { content: businessGlossaryUrl, description: `Pay for Introduction – experiment run in petcare vertical through which providers bought credits and used a credit for introduction to a seeker` },
  'Plib': { content: businessGlossaryUrl, description: `Pattern library. A project to templatize the UI design of our site` },
  'PAJ': { content: businessGlossaryUrl, description: `a form in the seeker enrollment flow that enables the seeker (for free without a premium as of Mar 2020) to post a job that providers can apply to` },
  'Post a job': { content: businessGlossaryUrl, description: `aka PAJ, is a form in the seeker enrollment flow that enables the seeker (for free without a premium as of Mar 2020) to post a job that providers can apply to` },
  'Preliminary Verification': { content: businessGlossaryUrl, description: `Another term for the basic check that is run on Premium Seekers` },
  'Premium Member': { content: businessGlossaryUrl, description: `Paying subscriber` },
  'Project X': { content: businessGlossaryUrl, description: `This was the “code name” for Carecheck that stuck for the Safety team` },
  'Provider': { content: businessGlossaryUrl, description: `Care.com member who is looking for a job and offering care services` },
  'Provider Network': { content: businessGlossaryUrl, description: `The Providers, Agencies and Centers in our network to match with Families` },
  'Rap Back': { content: businessGlossaryUrl, description: `Record of Arrest and Prosecutions Back, Rap Back is an optional Federal Bureau of Investigation (FBI) service that will allow authorized government agencies to receive notification of subsequent activity on individuals who hold positions of trust (e.g. school teachers, daycare workers) or who are under criminal justice supervision or investigation, thus eliminating the need for repeated background checks on a person from the same applicant agency.` },
  'Rate Card': { content: businessGlossaryUrl, description: `This is the page/screen offering a subscription to a user. At DB, we would’ve called this the subscription screen.` },
  'RDC': { content: businessGlossaryUrl, description: `Regulatory Data Check - 3rd party safety provider that flags users that are mentioned in news publications` },
  'Recruiting Services': { content: businessGlossaryUrl, description: `A component of Marketplace. Allows companies to post jobs and message caregiviers` },
  'Request to Book': { content: businessGlossaryUrl, description: `Feature that enables a seeker to book a provider for a specific day and time without posting a job` },
  'Resources': { content: careCoreUrl, description: `This is what Care.com refers to as its blog/website of articles (Care.com/c/)` },
  'S4': { content: businessGlossaryUrl, description: `legacy cross-functional team that reviewed and resolved safety issues` },
  'Safety Committee': { content: businessGlossaryUrl, description: `Cross-functional team that collaborates on safety issues across Care.com.  US Committee includes reps from Provider/Safety Product, Platform Product, Safety Ops, Safety Policy & Strategy, Legal, Communications, Business Intelligence.  INTL Committee includes reps from Product, Comms, Legal, Safety Ops, and Safety Policy & Strategy.` },
  'SC': { content: businessGlossaryUrl, description: `Senior Care ` },
  'Seeker': { content: businessGlossaryUrl, description: `Care.com member who is looking to hire a caregiver` },
  'Sift Science': { content: businessGlossaryUrl, description: `3rd party provider fraud detection tool that uses machine learning to identify potentially bad actors` },
  'Squad': { content: businessGlossaryUrl, description: `Product development team focused on a particular area` },
  'SMB': { content: businessGlossaryUrl, description: `Small & Midsize Business; we list a lot of SMB daycare & other providers on our site, which is a source of SEO traffic. This is a component of Marketplace` },
  'SSN': { content: businessGlossaryUrl, description: `Social Security Number` },
  'Sterling': { content: businessGlossaryUrl, description: `Our current exclusive vendor (as of January 2022) who runs CareChecks (Providers) and preliminary/basic checks (Seekers)` },
  'Tableau': { content: businessGlossaryUrl, description: `3rd party Data visualization tool` },
  'Town & Country': { content: businessGlossaryUrl, description: `SF nanny agency acquired by Care to meet enterprise SLAs` },
  'T&C': { content: businessGlossaryUrl, description: `SF nanny agency acquired by Care to meet enterprise SLAs` },
  'Trusted': { content: businessGlossaryUrl, description: `Backup care company acquired by Care acquired, SF-based` },
  'Vantiv': { content: businessGlossaryUrl, description: `Payment processor` },
  'VB CVR': { content: businessGlossaryUrl, description: `Visitor to Basic Conversion Rate` },
  'Verticals': { content: businessGlossaryUrl, description: `Childcare, Senior Care, Pet Care, Housekeeping, Tutoring, Special Needs` },
  'VHP': { content: businessGlossaryUrl, description: `Visitor Home Page` },
  'Vision Critical': { content: businessGlossaryUrl, description: `3rd party platform for our user research pool` },
  'VisX': { content: businessGlossaryUrl, description: `Visitor Experience` },
  'VOC': { content: businessGlossaryUrl, description: `Voice of Consumer – consumer research team` },
  'W-2': { content: businessGlossaryUrl, description: `Employee designation for “salaried employees”; companies withhold their W2 workers' Social Security and Medicare taxes, and pay employer payroll taxes. Non W-2 workers are generally independent contractors.` },
  // Care@Work Specific
  'BUC': { content: businessGlossaryUrl, description: `Abbreviation for Backup Care, the primary component of the C@W business.` },
  'PN': { content: businessGlossaryUrl, description: `Personal Network, where clients pay a friend or family member and are reimbursed by their employer.` },
  'Fillable Jobs': { content: businessGlossaryUrl, description: `Uncancelled BUC requests - the denominator in determining our fulfillment rate.` },
  'Filled Jobs': { content: businessGlossaryUrl, description: `BUC requests where care was successfully provided - the numerator in determining our fulfillment rate.` },
  'Proactive PN': { content: businessGlossaryUrl, description: `Personal Network request initiated by the client, either before care or up to 30 days after by submitting a reimbursement request with receipt. Some client don't include this in their contract due to the risk of abuse/fraud.  This is associated with Group Setting of 'Always' for Personal Network option of the corresponding Backup Care.` },
  'Reactive PN': { content: businessGlossaryUrl, description: `Personal Network request offered to clients only if/when we are unable to fulfill the request. Can only be created before care date & still requires that a receipt be submitted with reimbursement requests after the date of care. This conversion to an EIC claim is done by the CSR and is not available to seeker.  This is associated with Group Setting of 'When network is Unavailable' for Personal Network option of the corresponding Backup Care.` },
  // HomePay Specific
  'Prospect': { content: businessGlossaryUrl, description: ` A user who has started the enrollment process.` },
  'Care Asset': { content: businessGlossaryUrl, description: `A Defined Asset that lives on Care.com web pages that direct users to the HomePay MiniSite.` },
  'Client': { content: businessGlossaryUrl, description: `Prospects who have finished the enrollment process and started using the service.` },
  'HomePay Channel': { content: businessGlossaryUrl, description: `Segmentation used to split Prospects/Clients/Reactivations depending on their RX x HDYHAU, not applicable for MiniSite Visitors` },
  'HomePay HDYHAU': { content: businessGlossaryUrl, description: `How a Prospect/Client/Reactivation heard about Homepay, not applicable for MiniSite Visitors; "HDYHAU" - How Did You Hear About Us` },
  'HDYHAU': { content: businessGlossaryUrl, description: `How a Prospect/Client/Reactivation heard about Homepay, not applicable for MiniSite Visitors; "HDYHAU" - How Did You Hear About Us` },
  'HomePay Referral': { content: businessGlossaryUrl, description: `Segmentation used to split Visitors/Prospects/Clients/Reactivations depending on their RX information` },
  'MiniSite Prospects': { content: businessGlossaryUrl, description: `A user who started an Application via a Care.com HomePay MiniSite /homepay.` },
  'MiniSite Visitors': { content: businessGlossaryUrl, description: `A Visitor who went to the Care.com/homepay  Minisite.` },
  'Reactivation': { content: businessGlossaryUrl, description: `A Client who has reactivated their service account` },
  'Core MiniSite Visitors': { content: businessGlossaryUrl, description: `Subset of the overall Minisite visitors. Users have a CareCore Member ID but they are not Prospects or Clients` },
  'Leads': { content: businessGlossaryUrl, description: `Non-HomePay Prospects/Clients that have download or received marketing/informational material from HomePay` },
  'V/P': { content: businessGlossaryUrl, description: `MiniSite Visitors / Prospects - The conversion from Visitor → Prospect` },
  'Lead Prospects': { content: businessGlossaryUrl, description: `Prospects who were leads before becoming a prospect.` },
  'L/LP': { content: businessGlossaryUrl, description: `Lead Prospects / Leads - The conversion from Lead → Lead Prospect.` },
  'P/C': { content: businessGlossaryUrl, description: `Prospects / Clients - The conversion from Prospect → Clients` },
  'V/C': { content: businessGlossaryUrl, description: `MiniSite Visitor / Clients - The conversion from Visitor → Client` },
  'Total Stops': { content: businessGlossaryUrl, description: `Clients who are calling to stop their service over the course of time, measured on when they request to stop.` },
  // Lingo
  '3-Pings': { content: lingoUrl, description: `	A revenue report sent out via email 4 times a day at 9am, 12 noon, 4pm and 12 midnight.  Called "3-pings" because it was originally sent 3 times a day.` },
  'Activation Wizard': { content: lingoUrl, description: `A "Getting Started" flow that users automatically enter after enrolling. It helps them make the most of their account by making sure they have a photo uploaded, job posted, and so forth. It is testable so we can create different flows and test them against each other.` },
  'Adlob': { content: lingoUrl, description: `An "AD-Like OBject" -- Basically a spot we can advertise services, features, promotions, and more on Care.com.` },
  'Alfresco': { content: lingoUrl, description: `A legacy content management system used at Care, since replaced by Incasa and Wordpress as of 2021` },
  'Applicant': { content: lingoUrl, description: `A provider who has applied for a seeker's job.` },
  'Auth0': { content: lingoUrl, description: `Our identity provider platform provider` },
  'Axiom': { content: lingoUrl, description: `Our background check provider.` },
  'Big Bucket (report)': { content: lingoUrl, description: `A report sent out daily that breaks down traffic and sign ups by various marketing channels.` },
  'BFA': { content: lingoUrl, description: `"Background checks For All" - A background check we run on every member when they join the site. Also known as "Under the hood" checks.` },
  'BGC': { content: lingoUrl, description: `BackGround Checks: A CareSeeker likes to hire a reliable, experienced CareProvider. Care Platform provides a service for verifying a number of BGCs based on varied parameters, including, Driving License, Criminal Record, amongst various others` },
  'Basic Seeker': { content: lingoUrl, description: `A seeker who is not currently paying for a premium subscription -- they are at the free tier of membership.` },
  'BUC': { content: lingoUrl, description: `BackUp Care - Where the request for child care services is fulfilled by Care.com.` },
  'Care Exchange': { content: lingoUrl, description: `A way to use Care.com to 'exchange' services. For example, 2 sets of parents take turns watching each others' kids.` },
  'Care Match': { content: careMatchAndCareRankUrl, description: `	Our algorithm for determining how good a match a caregiver is to a particular job. Used to sort applicants. More detail: Care Match and Care Rank` },
  'Care Rank': { content: careMatchAndCareRankUrl, description: `Our algorithm for determining the relative quality of a caregiver as compared to all other caregivers.  Used as default sort order in search results.  More detail: Care Match and Care Rank` },
  'Care Smarts': { content: careSmartsUrl, description: `Our community Q&A platform: https://www.care.com/q/` },
  'Care-on-Call, Backup Care': { content: lingoUrl, description: `A way to post a last-minute care need to the site.  This creates a job posting then a special SMS alert goes out to up to 100 providers in the area that have specified they are available to provide 'last-minute' care.` },
  'CAREUS': { content: lingoUrl, description: `Name of JIRA-vertical used by Development and QA Teams for work management` },
  'CBUC': { content: lingoUrl, description: `Consumer BackUp Care - Where a premium seeker requests for backup care services.` },
  'CDC': { content: lingoUrl, description: `Change Data Capture - software patterns used to determine or track what data has changed over time` },
  'Cloud': { content: lingoUrl, description: `On a webpage, masking all content of the page and displaying an overlay. (More frequently known outside of Care.com as a 'modal pop up')` },
  'CMS': { content: lingoUrl, description: `"Content Management System"` },
  'Cobranding': { content: lingoUrl, description: `When two partner brands share the overall branding of a web page.  Our method of doing so is showing our logo and our partner's logo side-by-side.` },
  'CoE': { content: productManagementUrl, description: `Center of excellence - we have two established: Product Management and Technology` },
  'Convenience Payments': { content: lingoUrl, description: `Our feature that allows a family to pay a caregiver using their credit card, right on Care.com.` },
  'Cookie': { content: lingoUrl, description: `A cookie (also tracking cookie, browser cookie, and HTTP cookie) is a small piece of text stored on a user's computer by a web browser that let's the web site remember who the user is, track their movement across the website, and a number of other things.` },
  'CPAS': { content: lingoUrl, description: `"Cost Per Acquired Subscriber" - The advertising/marketing costs associated with acquiring a premium seeker.` },
  'CSR': { content: lingoUrl, description: `"Customer Services Representitive" or more often, our internal application that allows our member care representatives to search member profiles, approve content on the site, and more.` },
  'CTA': { content: lingoUrl, description: `"Call to Action" - a term used for something we want users to click` },
  'Cx': { content: lingoUrl, description: `Promo Code - An SEO URL parameter that allows us to pre-populate a promo code into a user's session.` },
  'Day 1 Premium': { content: lingoUrl, description: `A premium seeker that has purchased a premium subscription plan on the same day they first signed up for Care.com.` },
  'DT / MW': { content: lingoUrl, description: `DeskTop / Mobile Web - The Web implementation of Care Platform, Care.com, can either have a DeskTop web-view or a MobileWeb view` },
  'Dx': { content: lingoUrl, description: `"Cookie Days" - An SEO URL parameter that allows us to specify how long we should allow a user's cookies to last before they expire.  The site-wide default is 30-days.` },
  'DM': { content: lingoUrl, description: `Data Migration - Process of updating existing records or moving data from one environment to another. There is a dedicated team at Care.com which handles this operation.` },
  'DnA': { content: lingoUrl, description: `Design and Architecture group at Care` },
  'DNS (for BUC)': { content: lingoUrl, description: `Do Not Serve - A Backup Care setting. When set (e.g. answering yes to a question around Covid-19 and if you have been exposed): You cannot request backup care or log into the mobile app` },
  'EIC': { content: lingoUrl, description: `Employee Identified Care` },
  'Employer Program': { content: lingoUrl, description: `A Care.com line of business that gets an entire company to purchase a massive subscription to Care.com for all (or a subset of) their employees.` },
  'Enhanced Background Check': { content: lingoUrl, description: `A higher tier of background check that even premium seekers have to pay for.  Above the standard background check, this also includes a special "investigator" who checks federal and county courthouse records.  Some areas, this can be done electronically, whereas other areas they may have to physically go to the courthouse in question. Note: there is also an "Enhanced Background Check" which includes a Motor Vehicle Check` },
  'EBUC': { content: lingoUrl, description: `Employer BackUp Care - Where the seeker is an employee of a corporate client(Employer). Such seekers are also referred to as Groupies.` },
  'FTP': { content: lingoUrl, description: `Free Trial Premium - A CareSeeker can opt for a free trial of the premium services. FTP may not be available at all times` },
  'Fun Force': { content: lingoUrl, description: `The Fun Force is a team of Care.com employees who organize and run fun events throughout the year for Care.com. Past events have included happy hours, scavenger hunts, trivial nights, outings to sports events and more. Team members are selected by Sheila and announced each year at the annual holiday party.` },
  'Groups': { content: lingoUrl, description: `Groups is a platform on Care.com that allows users to create groups around communities, localities, or topics of interest.  These groups have discussion forums, events, announcements, file sharing (resources), and can even set up child care exchanges (Care Co-Ops).` },
  'HomePay': { content: lingoUrl, description: `Our Payroll and Tax service targeted to families who hire in-home care (e.g., Nannies).` },
  'IA': { content: lingoUrl, description: `"Information Architecture" or occasionally "Interaction Architecture" - This is the process of organizing information and functionality on a web page, taking into consideration what the primary objectives of the page are, what the user is likely to understand, and how we want them to interact with the page.` },
  'Incasa': { content: lingoUrl, description: `A Content Management System that was created in-house for managing changes` },
  'Jasper': { content: lingoUrl, description: `Jasper is a reporting application that allows users to run on-demand and scheduled reports.  It also serves as a data repository that archives scheduled reports.` },
  'Job': { content: lingoUrl, description: `A "job" is a way for a Seeker to advertise that they have an open care need (for example, they need to find a babysitter).  Seekers post jobs and providers can apply to them.` },
  'KCE': { content: lingoUrl, description: `KinderCare Education` },
  'L0': { content: lingoUrl, description: `L0 is the top-most level of navigation on the site.  Right now, this is the set of links found in the upper right of the page, e.g., "Log in", "Care Stories", "Employer Program", etc.` },
  'L1': { content: lingoUrl, description: `L1 is the main level of navigation on the site.  Right now, this is the main tabs, e.g., Children, Adults & Seniors, Pets, My Care.com, etc.` },
  'L2': { content: lingoUrl, description: `L2 is the secondary level of navigation below the L1 tabs.  These are found as the little menus that drop down when you hover over an L1 tab, e.g., if you hover over the Children tab, you are presented with "Babysitters & Nannies", "Au Pairs", and "Child Care Centers"` },
  'L3': { content: lingoUrl, description: `L3 is a third level of navigation, mainly found in My Care.com and My Groups.  This menu is on the left side of the page.` },
  'Lead Gen': { content: lingoUrl, description: `"Lead Generation" - This is a line of service where we charge companies to send them "leads"--users of our site who have opted to have their information sent to the company in question.` },
  'Liquidity': { content: lingoUrl, description: `The ability for us to service the needs of a seeker or provider on the platform. High provider liquidity means we have more providers on the platform that are available for jobs and it is easier for seekers to find a provider. High seeker liquidity means we have more seekers on the platform looking for jobs and it is easier for providers to find a job.` },
  'Litle': { content: lingoUrl, description: `Our credit card proccessing company for everything except Convenience Payments.` },
  'LTV': { content: lingoUrl, description: `"LifeTime Value"` },
  'M-Team	': { content: lingoUrl, description: `Management team (VPs and Officers)` },
  'Marketplace': { content: lingoUrl, description: `Our suite of B2B offerings.` },
  'Marketplace: Marketing Solutions': { content: lingoUrl, description: `The services that allow businesses to use our platform to market their business to our families (e.g., Child Care Centers advertising themselves).` },
  'Marketplace: Recruiting': { content: lingoUrl, description: `The services that allow businesses to recruit talent from our pool of caregivers (e.g., Child Care Centers trying to hire nannies to work for them directly).` },
  'Match': { content: lingoUrl, description: `	A "Match" is typically used to specify when a seeker makes the connection with a provider, but more specifically, we use it to indicate when a care seeker's need has been met--so they might have hired an individual provider, or entered their child into a day care, and so forth.` },
  'MFE': { content: lingoUrl, description: `"Micro Front End".  A user interface built on the Bravo platform (NodeJS, React, TypeScript, GraphQL, etc).` },
  'Monetate': { content: lingoUrl, description: `Testing / optimization platform mainly used by the marketing team to perform targeted / quick hit conversion tests without requiring a release` },
  'Monolith': { content: lingoUrl, description: `A large application or system built using older technologies and processes (ex: czen or BIS).` },
  'MHP': { content: lingoUrl, description: `"Member Home Page" – first page a user sees once they are logged in` },
  'MVR': { content: lingoUrl, description: `Motor Vehicle Registration - One of the BGCs available is validating the registration of CareProvider's Vehicle Registratoin` },
  'NCNY': { content: lingoUrl, description: `New Caregivers Near You - CareSeeker get notified on email, with the new caregiver profiles available to their preferred location.` },
  'NPS': { content: lingoUrl, description: `"Net Promoter Score" http://en.wikipedia.org/wiki/Net_Promoter` },
  'Nth Day': { content: lingoUrl, description: `A seeker who upgrades from basic to premium, but not on the same day they initially signed up for their care.com account.  (related: Day 1 Premium)` },
  'NJNY': { content: lingoUrl, description: `New Jobs Near You - CareProviders get notified on email, with the news jobs available to their preferred location` },
  'Omniture': { content: lingoUrl, description: `A set of tools that allow us to view many stats about how our users use our website.  It allows us to see how many people use the site and the paths they take through the site (among other things).` },
  'OTC': { content: lingoUrl, description: `One time care` },
  'PAJ': { content: lingoUrl, description: `"Post a job" – The step in Enrollment or Nth Day where a seeker can create a new job post` },
  'Perfect URL': { content: kindsOfUrlsUrl, description: `A type of URL that is especially user and SEO friendly.  It has no parameters or attributes as part of it.  Example: http://www.care.com/boston-babysitters - See more info here: Kinds of URLs` },
  'PiAP': { content: lingoUrl, description: `"Parents in a Pinch" - name of the Boston-based organization that was acquired by Care.com and is now powering our Backup Care platform` },
  'Pod Lunch': { content: lingoUrl, description: `"Pods" are groups of people who sit in the same general area (or at least that is how the "pod" concept was started). Every quarter a different pod organizes a company lunch. Past lunches have been quite memorable and have included singing contests (think American Idol), cook-outs, fashion shows (sort of), acting, and more. Every new employee is assigned to a pod. If you have not been assigned a pod yet, you will be soon!` },
  'PPR': { content: lingoUrl, description: `Pending Page Request - When care.com backend shows an Intermediate Page instead of showing the original requested Page. E.g. On a Successful Login, User is supposed to see the 'Member Home Page'. However, if the Member has gone to a "Pending Active" State, she/he is shown the "Pending Active" screen where Payment details needs to be entered again, making the original Page-View request go in a 'PPR' state.` },
  'Premium Seeker': { content: lingoUrl, description: `A premium seeker is a seeker who has a currently active, paid subscription.  There are ways to become "premium" without actually paying however (e.g., through employer program or through a free upgrade that we can give out), so it's important to know that this term typically includes folks that have comparable permissions on the site.` },
  'Project Champion': { content: lingoUrl, description: `This is the person that is considered the ultimate stakeholder of a new project, feature set, or initiative.  They are responsible for the ultimately guiding the decisions to meet their vision.` },
  'Provider': { content: lingoUrl, description: `A provider is a member of Care.com who is offering their care services, (a "care provider").  E.g., babysitter, nanny, tutor, dog walker, etc.` },
  'QA': { content: lingoUrl, description: `"Quality Assurance"` },
  'Recorded Reference': { content: lingoUrl, description: `This is a feature on provider's profiles on Care.com where we actually call one of their references and record a scripted interview with that reference.  An audio file of the interview is then posted to their profile and seekers can listen to it.` },
  'Requirements': { content: lingoUrl, description: `A "Requirements" document is a document that someone in the Product Management team typically writes in order to build a new (or improve on an existing) feature on the Care.com web site.  It documents most (ideally all) of the functional details that the engineers need to know in order to build the feature.` },
  'Retention': { content: lingoUrl, description: `This is a measurement of how long our paid members stick around as paid members before downgrading or closing their accounts.` },
  'Reupgrade': { content: lingoUrl, description: `When a basic seeker who has previous been a premium seeker upgrades again.` },
  'RTB': { content: lingoUrl, description: `Request to Book` },
  'Rx': { content: lingoUrl, description: `Referrer - An SEO URL parameter that allows us to specify marketing tracking codes and attribute traffic and signups to various marketing channels.` },
  'SalesForce': { content: lingoUrl, description: `	Our Customer Relationship Management (CRM) application.  It has a record for every member in our service so that our member care agents and sales agents can see all communication we've had with a specific member or company.` },
  'SCC': { content: lingoUrl, description: `Senior Care Consulting - A line of business where we develop a very detailed plan for the customer to fulfill their care needs. Typically sold to someone who is responsible for taking care of an elderly parent, relative, or so forth.` },
  'SCP': { content: lingoUrl, description: `Senior Care Planning` },
  'Scope': { content: lingoUrl, description: `This is an estimate of how much effort a project will take to build.  Generally, someone in Product Management will build a "Scope Document" which is like a requirements document that details, from a much higher level, all of the areas on the site we plan to change. It will also typically include a rough outline of the business logic we propose to introduce.  The engineering team uses this document to determine their "scope" of how long the project will take.` },
  'Seeker': { content: lingoUrl, description: `A seeker is a member of Care.com who is need of care services. E.g., parents looking to hire a nanny.` },
  'SEM': { content: lingoUrl, description: `"Search Engine Marketing" - Specifically, paid search engine advertising. E.g., when we bid on particular keywords to appear in the "sponsored listings" section of Google.` },
  'SEO': { content: lingoUrl, description: `"Search Engine Optimization" - Efforts centered around increasing the ranking of our pages in search engines to increase traffic--and ultimately conversion--of users who find us in "organic" search results on a search engine. Organic search listings are the results that are not in the "sponsored listings."` },
  'SEO URL': { content: kindsOfUrlsUrl, description: `A feature we have on our site that allows us to specify URLs that have a number of features. See more detail here: Kinds of URLs` },
  'SMB': { content: lingoUrl, description: `"Small and Medium Business" - Former name of our B2B "Marketplace" product` },
  'Spike': { content: lingoUrl, description: `Investigation stories. Things unknown that need further research. Output will likely be a proposal for solution and possibly a proof-of-concept.` },
  'Staging': { content: lingoUrl, description: `Staging is a copy of Care.com, found at http://www.carestage.com/ .  This copy of our website is used to test various new features before they go live to the world at large. For security reasons, we scrub (mask or delete) some information here, such as social security numbers, credit cards, last names, and birthdates.` },
  'Standard Background Check': { content: lingoUrl, description: `A standard background check is our regular tier of background check that premium seekers may run on providers or providers may opt to pay to run on themselves. This is an electronic check that typically includes a national criminal database search, social security verification, and national sex offender database search. I say "typically" because what it actually includes may vary from state to state.` },
  'Sterling': { content: lingoUrl, description: `Could be referring to a background check provider OR the Care.com international web platform` },
  'Sticky Test Cell (report)': { content: lingoUrl, description: `This is a report used to measure the effectiveness of various testing initiatives, e.g., testing different versions of the Visitor Home Page against each other.  It can be found in Jasper.` },
  'Test Cell': { content: lingoUrl, description: `In testing, a use a "test cell" to refer to one of the versions being tested.` },
  'Test Cell Weight': { content: lingoUrl, description: `Each test cell may have a weight: this is a percentage of the user-base that should see this particular test cell.` },
  'TO': { content: lingoUrl, description: `(Technical Operations?) 1. Production & Operations Team (Prod Opts Team) which maintains deployment and Data-Migration (DM) for our application, care.com 2. Name of JIRA Vertical used by Prod Opts Team for Work Management` },
  'U18 Provider / Parent': { content: lingoUrl, description: `We have special account status for providers who are under 18 years old when they join the platform - these providers require that a parent set up a linked account that allows them to receive all messages and monitor account activity.` },
  'U-Team': { content: lingoUrl, description: `	"User Experience Team" - This is a cross functional group of people who focus on improving user experience for users of our service.  They analyze our biggest complaints and focus on bringing up NPS.` },
  'UAT': { content: lingoUrl, description: `"User Acceptance Testing"` },
  'UBGC': { content: lingoUrl, description: `Unlimited BGC - One of the available packages for Subscription are Unlimited BGCs during a specified time period, where the time period and charges involved may vary` },
  'UI': { content: lingoUrl, description: `"User Interface" - What the user sees and interacts with on the website.` },
  'Upgrade': { content: lingoUrl, description: `When a basic seeker pays to become a premium seeker.` },
  'Vanity URL': { content: kindsOfUrlsUrl, description: `A vanity URL is a friendly, temporary URL that can be used to make things easier for print purposes or to give to partners. For more information, see: Kinds of URLs` },
  'Vertical': { content: lingoUrl, description: `"Verticals" are the different categories of services we offer, e.g., Child Care, Pet Care, Senior Care, and Housekeeping.` },
  'VHP': { content: lingoUrl, description: `"Visitor Home Page" - Refers to the Home page of the our application, www.care.com` },
  'Vision': { content: lingoUrl, description: `Vision is the objectives and very high level strategy of a particular feature, set of enhancements, or test that will be added to or conducted on Care.com.  Typically, the vision document will be written jointly by a particular projects "Champion" and representatives from Product Management and Product Marketing.` },
  'Vision Document': { content: lingoUrl, description: `Vision is the objectives and very high level strategy of a particular feature, set of enhancements, or test that will be added to or conducted on Care.com.  Typically, the vision document will be written jointly by a particular projects "Champion" and representatives from Product Management and Product Marketing.` },
  'Visitor Experience': { content: lingoUrl, description: `The VISX platform is a separate experience that is targeted to non-members visiting the site, intentionally separate from the logged in Member Experience for users. This platform is focused on being optimized for SEO and member acquisition, and pages are designed in the responsive design templates to serve an experience for desktop and mobile.` },
  'VISX': { content: lingoUrl, description: `The VISX platform is a separate experience that is targeted to non-members visiting the site, intentionally separate from the logged in Member Experience for users. This platform is focused on being optimized for SEO and member acquisition, and pages are designed in the responsive design templates to serve an experience for desktop and mobile.` },
  'WePay': { content: lingoUrl, description: `Our payment processing partner specifically for the Convenience Payments feature.` },
  'WF': { content: lingoUrl, description: `Wells Fargo (bank)` },
  'WFH': { content: lingoUrl, description: `"Working From Home"` },
  'Wireframe': { content: lingoUrl, description: `Wireframe is a low fidelity (quick and dirty, black and white, and occasionally paper and pencil) sketchup of what a proposed new page (or new functionality on an existing page) should look like.  The wireframe is created so that "IA" can be discussed without getting into too many details on colors, icons, photos, and other design elements.` },
  'Workplace Solutions': { content: lingoUrl, description: `aka WPS, aka C@W - Selling Care.com products and services to businesses to use as employee benefits.` },
  // Provider Terms
  'Tinder': { content: tinderUrl, description: `User experience in which job search results are presented 1-by-1, like the Tinder dating app experience. Currently present for all searches for all Providers with a Pet Care profile.` },
  'Pay to Unlock': { content: payToUnlockUrl, description: `User experience in which a Basic Provider's application to a Basic Seeker job is masked in the Provider's own inbox/outbox, with a CTA to upgrade to allow the Basic Seeker to respond.` },
  'P2U': { content: lingoUrl, description: `User experience in which a Basic Provider's application to a Basic Seeker job is masked in the Provider's own inbox/outbox, with a CTA to upgrade to allow the Basic Seeker to respond.` },
  'Message Masking': { content: lingoUrl, description: `Basic Seeker's P2U mirror experience, in which a Basic Provider's job application is masked with a CTA to upgrade in Basic Seeker's inbox.` },
  'PayFI/Hybrid': { content: lingoUrl, description: `User experience in which Providers must use credits to apply to jobs. (From Pay For Introduction)` },
  'U18/Teen Caregivers/Providers': { content: teenProviderGuidelinesUrl, description: `Providers who are under the age of 18 and therefore have a unique member experience.` },
  'NJNY': { content: lingoUrl, description: `New Jobs Near You: emails sent 1-2x/daily to Providers and Seekers respectively.` },
  'NCNY': { content: lingoUrl, description: `New Caregivers Near You: emails sent 1-2x/daily to Providers and Seekers respectively.` },
}

// Format with XML for the omnibox suggestion list
const definitions = Object.keys(terms).reduce( (definitions, term) => {
  const content = terms[term].content
  const description = `<match>${term}</match> - <dim>${terms[term].description}</dim>`
  return { ...definitions, [term.toLowerCase()]: { content, description }}
}, {})

const defaultSuggestion = { description: `<dim>Type an abbreviation to see it's definition below</dim>` }

const handleInputChanged = (text, suggest) => {
  const suggestion = definitions[text.toLowerCase()]
  if (suggestion) suggest([suggestion])
  else suggest([])
}

const handleInputEntered = (text, disposition) => {
  const suggestion = definitions[text.toUpperCase()]
  const url = suggestion ? suggestion.content : lingoUrl
  if (disposition === 'currentTab') chrome.tabs.update({url})
  if (disposition === 'newForegroundTab') chrome.tabs.create({url})
  if (disposition === 'newBackgroundTab') browser.tabs.create({url, active: false})
}

chrome.omnibox.setDefaultSuggestion(defaultSuggestion)
chrome.omnibox.onInputChanged.addListener(handleInputChanged)
chrome.omnibox.onInputEntered.addListener(handleInputEntered)